function runAnimations() {
  document.querySelector("#id-13216").addEventListener("click", func_13216_112);

  function func_13216_112(e) {
    e.stopPropagation();

    document.querySelector("#id-112").classList.add("animationClass-112");
    document
      .querySelector(".hello-user-1-41850-0")
      .classList.add("animationClass-114-114-0");
    document.querySelector("#id-114").classList.add("animationClass-114");
    document.querySelector("#id-163").classList.add("animationClass-163");
    document.querySelector("#id-119").classList.add("animationClass-119");
    document
      .querySelector(".selfcomposed-1-458990-0")
      .classList.add("animationClass-120-120-0");
    document.querySelector("#id-120").classList.add("animationClass-120");
    document.querySelector("#id-1320").classList.add("animationClass-1320");
    document.querySelector("#id-115").classList.add("animationClass-115");
    document
      .querySelector(".how-are-you-fee-1-51250-0")
      .classList.add("animationClass-180-180-0");
    document.querySelector("#id-180").classList.add("animationClass-180");
    document.querySelector("#id-13215").classList.add("animationClass-13215");
    document.querySelector("#id-13216").classList.add("animationClass-13216");
    document.querySelector("#id-13217").classList.add("animationClass-13217");
    document
      .querySelector(".home-1-55242-0")
      .classList.add("animationClass-13218-13218-0");
    document.querySelector("#id-13218").classList.add("animationClass-13218");
    document.querySelector("#id-13219").classList.add("animationClass-13219");
    document.querySelector("#id-13220").classList.add("animationClass-13220");
    document
      .querySelector(".journaling-1-77080-0")
      .classList.add("animationClass-13221-13221-0");
    document.querySelector("#id-13221").classList.add("animationClass-13221");
    document.querySelector("#id-13222").classList.add("animationClass-13222");
    document.querySelector("#id-13223").classList.add("animationClass-13223");
    document
      .querySelector(".selfcare-1-21280-0")
      .classList.add("animationClass-13224-13224-0");
    document.querySelector("#id-13224").classList.add("animationClass-13224");
    document.querySelector("#id-13225").classList.add("animationClass-13225");
    document.querySelector("#id-13226").classList.add("animationClass-13226");
    document
      .querySelector(".profile-1-469098-0")
      .classList.add("animationClass-13227-13227-0");
    document.querySelector("#id-13227").classList.add("animationClass-13227");
    document.querySelector("#id-726").classList.add("animationClass-726");
    document.querySelector("#id-725").classList.add("animationClass-725");
    document.querySelector("#id-116").classList.add("animationClass-116");
    document
      .querySelector(".journaling-prom-2-157440-0")
      .classList.add("animationClass-1321-1321-0");
    document.querySelector("#id-1321").classList.add("animationClass-1321");
    document.querySelector("#id-723").classList.add("animationClass-723");
    document.querySelector("#id-72").classList.add("animationClass-72");
    document.querySelector("#id-713").classList.add("animationClass-713");
    document.querySelector("#id-711").classList.add("animationClass-711");
    document.querySelector("#id-712").classList.add("animationClass-712");
    document.querySelector("#id-724").classList.add("animationClass-724");
    document.querySelector("#id-117").classList.add("animationClass-117");
    document
      .querySelector(".daily-tasks-1-687675-0")
      .classList.add("animationClass-1322-1322-0");
    document.querySelector("#id-1322").classList.add("animationClass-1322");
    document.querySelector("#id-722").classList.add("animationClass-722");
    document.querySelector("#id-73").classList.add("animationClass-73");
    document.querySelector("#id-715").classList.add("animationClass-715");
    document.querySelector("#id-716").classList.add("animationClass-716");
    document.querySelector("#id-717").classList.add("animationClass-717");
    document.querySelector("#id-721").classList.add("animationClass-721");
    document.querySelector("#id-74").classList.add("animationClass-74");
    document.querySelector("#id-718").classList.add("animationClass-718");
    document.querySelector("#id-719").classList.add("animationClass-719");
    document.querySelector("#id-720").classList.add("animationClass-720");
    document
      .querySelector("#id-13216")
      .removeEventListener("click", func_13216_112);

    setTimeout(() => {
      //loop login
      document.querySelector("#id-112").classList.remove("animationClass-112");
      document
        .querySelector(".hello-user-1-41850-0")
        .classList.remove("animationClass-114-114-0");
      document.querySelector("#id-114").classList.remove("animationClass-114");
      document.querySelector("#id-163").classList.remove("animationClass-163");
      document.querySelector("#id-119").classList.remove("animationClass-119");
      document
        .querySelector(".selfcomposed-1-458990-0")
        .classList.remove("animationClass-120-120-0");
      document.querySelector("#id-120").classList.remove("animationClass-120");
      document
        .querySelector("#id-1320")
        .classList.remove("animationClass-1320");
      document.querySelector("#id-115").classList.remove("animationClass-115");
      document
        .querySelector(".how-are-you-fee-1-51250-0")
        .classList.remove("animationClass-180-180-0");
      document.querySelector("#id-180").classList.remove("animationClass-180");
      document
        .querySelector("#id-13215")
        .classList.remove("animationClass-13215");
      document
        .querySelector("#id-13216")
        .classList.remove("animationClass-13216");
      document
        .querySelector("#id-13217")
        .classList.remove("animationClass-13217");
      document
        .querySelector(".home-1-55242-0")
        .classList.remove("animationClass-13218-13218-0");
      document
        .querySelector("#id-13218")
        .classList.remove("animationClass-13218");
      document
        .querySelector("#id-13219")
        .classList.remove("animationClass-13219");
      document
        .querySelector("#id-13220")
        .classList.remove("animationClass-13220");
      document
        .querySelector(".journaling-1-77080-0")
        .classList.remove("animationClass-13221-13221-0");
      document
        .querySelector("#id-13221")
        .classList.remove("animationClass-13221");
      document
        .querySelector("#id-13222")
        .classList.remove("animationClass-13222");
      document
        .querySelector("#id-13223")
        .classList.remove("animationClass-13223");
      document
        .querySelector(".selfcare-1-21280-0")
        .classList.remove("animationClass-13224-13224-0");
      document
        .querySelector("#id-13224")
        .classList.remove("animationClass-13224");
      document
        .querySelector("#id-13225")
        .classList.remove("animationClass-13225");
      document
        .querySelector("#id-13226")
        .classList.remove("animationClass-13226");
      document
        .querySelector(".profile-1-469098-0")
        .classList.remove("animationClass-13227-13227-0");
      document
        .querySelector("#id-13227")
        .classList.remove("animationClass-13227");
      document.querySelector("#id-726").classList.remove("animationClass-726");
      document.querySelector("#id-725").classList.remove("animationClass-725");
      document.querySelector("#id-116").classList.remove("animationClass-116");
      document
        .querySelector(".journaling-prom-2-157440-0")
        .classList.remove("animationClass-1321-1321-0");
      document
        .querySelector("#id-1321")
        .classList.remove("animationClass-1321");
      document.querySelector("#id-723").classList.remove("animationClass-723");
      document.querySelector("#id-72").classList.remove("animationClass-72");
      document.querySelector("#id-713").classList.remove("animationClass-713");
      document.querySelector("#id-711").classList.remove("animationClass-711");
      document.querySelector("#id-712").classList.remove("animationClass-712");
      document.querySelector("#id-724").classList.remove("animationClass-724");
      document.querySelector("#id-117").classList.remove("animationClass-117");
      document
        .querySelector(".daily-tasks-1-687675-0")
        .classList.remove("animationClass-1322-1322-0");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-1322");
      document.querySelector("#id-722").classList.remove("animationClass-722");
      document.querySelector("#id-73").classList.remove("animationClass-73");
      document.querySelector("#id-715").classList.remove("animationClass-715");
      document.querySelector("#id-716").classList.remove("animationClass-716");
      document.querySelector("#id-717").classList.remove("animationClass-717");
      document.querySelector("#id-721").classList.remove("animationClass-721");
      document.querySelector("#id-74").classList.remove("animationClass-74");
      document.querySelector("#id-718").classList.remove("animationClass-718");
      document.querySelector("#id-719").classList.remove("animationClass-719");
      document.querySelector("#id-720").classList.remove("animationClass-720");
      runAnimations();
    }, 300);
  }
}
export default runAnimations;
// links object
export const allLinks = {};

// function object
export const allFunctions = {};
