function runAnimations() {
  document.querySelector("#id-1323").addEventListener("click", func_1323_112);

  function func_1323_112(e) {
    e.stopPropagation();

    document.querySelector("#id-113").classList.add("animationClass-113");
    document.querySelector("#id-114").classList.add("animationClass-null114");
    document.querySelector("#id-7272").classList.add("animationClass-7272");
    document.querySelector("#id-7273").classList.add("animationClass-7273");
    document
      .querySelector(".selfcomposed-1-26795-0")
      .classList.add("animationClass-7274-7274-0");
    document.querySelector("#id-7274").classList.add("animationClass-7274");
    document.querySelector("#id-6575").classList.add("animationClass-6575");
    document.querySelector("#id-6574").classList.add("animationClass-6574");
    document.querySelector("#id-1322").classList.add("animationClass-1322");
    document.querySelector("#id-1323").classList.add("animationClass-1323");
    document.querySelector("#id-1324").classList.add("animationClass-1324");
    document
      .querySelector(".home-1-630601-0")
      .classList.add("animationClass-1325-1325-0");
    document.querySelector("#id-1325").classList.add("animationClass-1325");
    document.querySelector("#id-1326").classList.add("animationClass-1326");
    document.querySelector("#id-1327").classList.add("animationClass-1327");
    document
      .querySelector(".journaling-1-15025-0")
      .classList.add("animationClass-1328-1328-0");
    document.querySelector("#id-1328").classList.add("animationClass-1328");
    document.querySelector("#id-1329").classList.add("animationClass-1329");
    document.querySelector("#id-13210").classList.add("animationClass-13210");
    document
      .querySelector(".selfcare-1-559602-0")
      .classList.add("animationClass-13211-13211-0");
    document.querySelector("#id-13211").classList.add("animationClass-13211");
    document.querySelector("#id-13212").classList.add("animationClass-13212");
    document.querySelector("#id-13213").classList.add("animationClass-13213");
    document
      .querySelector(".profile-1-239391-0")
      .classList.add("animationClass-13214-13214-0");
    document.querySelector("#id-13214").classList.add("animationClass-13214");
    document.querySelector("#id-7251").classList.add("animationClass-7251");
    document.querySelector("#id-6588").classList.add("animationClass-6588");
    document.querySelector("#id-1320").classList.add("animationClass-null1320");
    document.querySelector("#id-115").classList.add("animationClass-null115");
    document.querySelector("#id-180").classList.add("animationClass-null180");
    document.querySelector("#id-726").classList.add("animationClass-null726");
    document.querySelector("#id-725").classList.add("animationClass-null725");
    document.querySelector("#id-116").classList.add("animationClass-null116");
    document.querySelector("#id-1321").classList.add("animationClass-null1321");
    document.querySelector("#id-723").classList.add("animationClass-null723");
    document.querySelector("#id-72").classList.add("animationClass-null72");
    document.querySelector("#id-713").classList.add("animationClass-null713");
    document.querySelector("#id-711").classList.add("animationClass-null711");
    document.querySelector("#id-712").classList.add("animationClass-null712");
    document.querySelector("#id-724").classList.add("animationClass-null724");
    document.querySelector("#id-117").classList.add("animationClass-null117");
    document.querySelector("#id-1322").classList.add("animationClass-null1322");
    document.querySelector("#id-722").classList.add("animationClass-null722");
    document.querySelector("#id-73").classList.add("animationClass-null73");
    document.querySelector("#id-715").classList.add("animationClass-null715");
    document.querySelector("#id-716").classList.add("animationClass-null716");
    document.querySelector("#id-717").classList.add("animationClass-null717");
    document.querySelector("#id-721").classList.add("animationClass-null721");
    document.querySelector("#id-74").classList.add("animationClass-null74");
    document.querySelector("#id-718").classList.add("animationClass-null718");
    document.querySelector("#id-719").classList.add("animationClass-null719");
    document.querySelector("#id-720").classList.add("animationClass-null720");
    document.querySelector("#id-6593").classList.add("animationClass-6593");
    document
      .querySelector("#id-1323")
      .removeEventListener("click", func_1323_112);

    setTimeout(() => {
      document
        .querySelector("#id-1323")
        .addEventListener("click", func_1323_112);
    }, 100);
  }

  function func_1323_112(e) {
    e.stopPropagation();

    document.querySelector("#id-113").classList.add("animationClass-112");
    document
      .querySelector(".hello-user1-0-71638-0")
      .classList.add("animationClass-114-114-0");
    document.querySelector("#id-114").classList.add("animationClass-114");
    document.querySelector("#id-7272").classList.add("animationClass-163");
    document.querySelector("#id-7273").classList.add("animationClass-119");
    document
      .querySelector(".selfcomposed-1-26795-0")
      .classList.add("animationClass-120-120-0");
    document.querySelector("#id-7274").classList.add("animationClass-120");
    document.querySelector("#id-6575").classList.add("nullAnimation-6575");
    document.querySelector("#id-6574").classList.add("nullAnimation-6574");
    document.querySelector("#id-1322").classList.add("animationClass-13215");
    document.querySelector("#id-1323").classList.add("animationClass-13216");
    document.querySelector("#id-1324").classList.add("animationClass-13217");
    document
      .querySelector(".home-1-630601-0")
      .classList.add("animationClass-13218-13218-0");
    document.querySelector("#id-1325").classList.add("animationClass-13218");
    document.querySelector("#id-1326").classList.add("animationClass-13219");
    document.querySelector("#id-1327").classList.add("animationClass-13220");
    document
      .querySelector(".journaling-1-15025-0")
      .classList.add("animationClass-13221-13221-0");
    document.querySelector("#id-1328").classList.add("animationClass-13221");
    document.querySelector("#id-1329").classList.add("animationClass-13222");
    document.querySelector("#id-13210").classList.add("animationClass-13223");
    document
      .querySelector(".selfcare-1-559602-0")
      .classList.add("animationClass-13224-13224-0");
    document.querySelector("#id-13211").classList.add("animationClass-13224");
    document.querySelector("#id-13212").classList.add("animationClass-13225");
    document.querySelector("#id-13213").classList.add("animationClass-13226");
    document
      .querySelector(".profile-1-239391-0")
      .classList.add("animationClass-13227-13227-0");
    document.querySelector("#id-13214").classList.add("animationClass-13227");
    document.querySelector("#id-7251").classList.add("nullAnimation-7251");
    document.querySelector("#id-6588").classList.add("nullAnimation-6588");
    document.querySelector("#id-1320").classList.add("animationClass-1320");
    document.querySelector("#id-115").classList.add("animationClass-115");
    document
      .querySelector(".how-are-you-fee-1-256025-0")
      .classList.add("animationClass-180-180-0");
    document.querySelector("#id-180").classList.add("animationClass-180");
    document.querySelector("#id-726").classList.add("animationClass-726");
    document.querySelector("#id-725").classList.add("animationClass-725");
    document.querySelector("#id-116").classList.add("animationClass-116");
    document
      .querySelector(".journaling-prom-2-268705-0")
      .classList.add("animationClass-1321-1321-0");
    document.querySelector("#id-1321").classList.add("animationClass-1321");
    document.querySelector("#id-723").classList.add("animationClass-723");
    document.querySelector("#id-72").classList.add("animationClass-72");
    document.querySelector("#id-713").classList.add("animationClass-713");
    document.querySelector("#id-711").classList.add("animationClass-711");
    document.querySelector("#id-712").classList.add("animationClass-712");
    document.querySelector("#id-724").classList.add("animationClass-724");
    document.querySelector("#id-117").classList.add("animationClass-117");
    document
      .querySelector(".daily-tasks-1-192132-0")
      .classList.add("animationClass-1322-1322-0");
    document.querySelector("#id-1322").classList.add("animationClass-1322");
    document.querySelector("#id-722").classList.add("animationClass-722");
    document.querySelector("#id-73").classList.add("animationClass-73");
    document.querySelector("#id-715").classList.add("animationClass-715");
    document.querySelector("#id-716").classList.add("animationClass-716");
    document.querySelector("#id-717").classList.add("animationClass-717");
    document.querySelector("#id-721").classList.add("animationClass-721");
    document.querySelector("#id-74").classList.add("animationClass-74");
    document.querySelector("#id-718").classList.add("animationClass-718");
    document.querySelector("#id-719").classList.add("animationClass-719");
    document.querySelector("#id-720").classList.add("animationClass-720");
    document.querySelector("#id-6593").classList.add("nullAnimation-6593");
    document
      .querySelector("#id-1323")
      .removeEventListener("click", func_1323_112);

    setTimeout(() => {
      //loop login
      document.querySelector("#id-113").classList.remove("animationClass-113");
      document
        .querySelector("#id-114")
        .classList.remove("animationClass-null114");
      document
        .querySelector("#id-7272")
        .classList.remove("animationClass-7272");
      document
        .querySelector("#id-7273")
        .classList.remove("animationClass-7273");
      document
        .querySelector(".selfcomposed-1-26795-0")
        .classList.remove("animationClass-7274-7274-0");
      document
        .querySelector("#id-7274")
        .classList.remove("animationClass-7274");
      document
        .querySelector("#id-6575")
        .classList.remove("animationClass-6575");
      document
        .querySelector("#id-6574")
        .classList.remove("animationClass-6574");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-1322");
      document
        .querySelector("#id-1323")
        .classList.remove("animationClass-1323");
      document
        .querySelector("#id-1324")
        .classList.remove("animationClass-1324");
      document
        .querySelector(".home-1-630601-0")
        .classList.remove("animationClass-1325-1325-0");
      document
        .querySelector("#id-1325")
        .classList.remove("animationClass-1325");
      document
        .querySelector("#id-1326")
        .classList.remove("animationClass-1326");
      document
        .querySelector("#id-1327")
        .classList.remove("animationClass-1327");
      document
        .querySelector(".journaling-1-15025-0")
        .classList.remove("animationClass-1328-1328-0");
      document
        .querySelector("#id-1328")
        .classList.remove("animationClass-1328");
      document
        .querySelector("#id-1329")
        .classList.remove("animationClass-1329");
      document
        .querySelector("#id-13210")
        .classList.remove("animationClass-13210");
      document
        .querySelector(".selfcare-1-559602-0")
        .classList.remove("animationClass-13211-13211-0");
      document
        .querySelector("#id-13211")
        .classList.remove("animationClass-13211");
      document
        .querySelector("#id-13212")
        .classList.remove("animationClass-13212");
      document
        .querySelector("#id-13213")
        .classList.remove("animationClass-13213");
      document
        .querySelector(".profile-1-239391-0")
        .classList.remove("animationClass-13214-13214-0");
      document
        .querySelector("#id-13214")
        .classList.remove("animationClass-13214");
      document
        .querySelector("#id-7251")
        .classList.remove("animationClass-7251");
      document
        .querySelector("#id-6588")
        .classList.remove("animationClass-6588");
      document
        .querySelector("#id-1320")
        .classList.remove("animationClass-null1320");
      document
        .querySelector("#id-115")
        .classList.remove("animationClass-null115");
      document
        .querySelector("#id-180")
        .classList.remove("animationClass-null180");
      document
        .querySelector("#id-726")
        .classList.remove("animationClass-null726");
      document
        .querySelector("#id-725")
        .classList.remove("animationClass-null725");
      document
        .querySelector("#id-116")
        .classList.remove("animationClass-null116");
      document
        .querySelector("#id-1321")
        .classList.remove("animationClass-null1321");
      document
        .querySelector("#id-723")
        .classList.remove("animationClass-null723");
      document
        .querySelector("#id-72")
        .classList.remove("animationClass-null72");
      document
        .querySelector("#id-713")
        .classList.remove("animationClass-null713");
      document
        .querySelector("#id-711")
        .classList.remove("animationClass-null711");
      document
        .querySelector("#id-712")
        .classList.remove("animationClass-null712");
      document
        .querySelector("#id-724")
        .classList.remove("animationClass-null724");
      document
        .querySelector("#id-117")
        .classList.remove("animationClass-null117");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-null1322");
      document
        .querySelector("#id-722")
        .classList.remove("animationClass-null722");
      document
        .querySelector("#id-73")
        .classList.remove("animationClass-null73");
      document
        .querySelector("#id-715")
        .classList.remove("animationClass-null715");
      document
        .querySelector("#id-716")
        .classList.remove("animationClass-null716");
      document
        .querySelector("#id-717")
        .classList.remove("animationClass-null717");
      document
        .querySelector("#id-721")
        .classList.remove("animationClass-null721");
      document
        .querySelector("#id-74")
        .classList.remove("animationClass-null74");
      document
        .querySelector("#id-718")
        .classList.remove("animationClass-null718");
      document
        .querySelector("#id-719")
        .classList.remove("animationClass-null719");
      document
        .querySelector("#id-720")
        .classList.remove("animationClass-null720");
      document
        .querySelector("#id-6593")
        .classList.remove("animationClass-6593");
      document.querySelector("#id-113").classList.remove("animationClass-112");
      document
        .querySelector(".hello-user1-0-71638-0")
        .classList.remove("animationClass-114-114-0");
      document.querySelector("#id-114").classList.remove("animationClass-114");
      document.querySelector("#id-7272").classList.remove("animationClass-163");
      document.querySelector("#id-7273").classList.remove("animationClass-119");
      document
        .querySelector(".selfcomposed-1-26795-0")
        .classList.remove("animationClass-120-120-0");
      document.querySelector("#id-7274").classList.remove("animationClass-120");
      document.querySelector("#id-6575").classList.remove("nullAnimation-6575");
      document.querySelector("#id-6574").classList.remove("nullAnimation-6574");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-13215");
      document
        .querySelector("#id-1323")
        .classList.remove("animationClass-13216");
      document
        .querySelector("#id-1324")
        .classList.remove("animationClass-13217");
      document
        .querySelector(".home-1-630601-0")
        .classList.remove("animationClass-13218-13218-0");
      document
        .querySelector("#id-1325")
        .classList.remove("animationClass-13218");
      document
        .querySelector("#id-1326")
        .classList.remove("animationClass-13219");
      document
        .querySelector("#id-1327")
        .classList.remove("animationClass-13220");
      document
        .querySelector(".journaling-1-15025-0")
        .classList.remove("animationClass-13221-13221-0");
      document
        .querySelector("#id-1328")
        .classList.remove("animationClass-13221");
      document
        .querySelector("#id-1329")
        .classList.remove("animationClass-13222");
      document
        .querySelector("#id-13210")
        .classList.remove("animationClass-13223");
      document
        .querySelector(".selfcare-1-559602-0")
        .classList.remove("animationClass-13224-13224-0");
      document
        .querySelector("#id-13211")
        .classList.remove("animationClass-13224");
      document
        .querySelector("#id-13212")
        .classList.remove("animationClass-13225");
      document
        .querySelector("#id-13213")
        .classList.remove("animationClass-13226");
      document
        .querySelector(".profile-1-239391-0")
        .classList.remove("animationClass-13227-13227-0");
      document
        .querySelector("#id-13214")
        .classList.remove("animationClass-13227");
      document.querySelector("#id-7251").classList.remove("nullAnimation-7251");
      document.querySelector("#id-6588").classList.remove("nullAnimation-6588");
      document
        .querySelector("#id-1320")
        .classList.remove("animationClass-1320");
      document.querySelector("#id-115").classList.remove("animationClass-115");
      document
        .querySelector(".how-are-you-fee-1-256025-0")
        .classList.remove("animationClass-180-180-0");
      document.querySelector("#id-180").classList.remove("animationClass-180");
      document.querySelector("#id-726").classList.remove("animationClass-726");
      document.querySelector("#id-725").classList.remove("animationClass-725");
      document.querySelector("#id-116").classList.remove("animationClass-116");
      document
        .querySelector(".journaling-prom-2-268705-0")
        .classList.remove("animationClass-1321-1321-0");
      document
        .querySelector("#id-1321")
        .classList.remove("animationClass-1321");
      document.querySelector("#id-723").classList.remove("animationClass-723");
      document.querySelector("#id-72").classList.remove("animationClass-72");
      document.querySelector("#id-713").classList.remove("animationClass-713");
      document.querySelector("#id-711").classList.remove("animationClass-711");
      document.querySelector("#id-712").classList.remove("animationClass-712");
      document.querySelector("#id-724").classList.remove("animationClass-724");
      document.querySelector("#id-117").classList.remove("animationClass-117");
      document
        .querySelector(".daily-tasks-1-192132-0")
        .classList.remove("animationClass-1322-1322-0");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-1322");
      document.querySelector("#id-722").classList.remove("animationClass-722");
      document.querySelector("#id-73").classList.remove("animationClass-73");
      document.querySelector("#id-715").classList.remove("animationClass-715");
      document.querySelector("#id-716").classList.remove("animationClass-716");
      document.querySelector("#id-717").classList.remove("animationClass-717");
      document.querySelector("#id-721").classList.remove("animationClass-721");
      document.querySelector("#id-74").classList.remove("animationClass-74");
      document.querySelector("#id-718").classList.remove("animationClass-718");
      document.querySelector("#id-719").classList.remove("animationClass-719");
      document.querySelector("#id-720").classList.remove("animationClass-720");
      document.querySelector("#id-6593").classList.remove("nullAnimation-6593");
      runAnimations();
    }, 300);
  }
}
export default runAnimations;
// links object
export const allLinks = {};

// function object
export const allFunctions = {};
