function runAnimations() {
  document.querySelector("#id-13442").addEventListener("click", func_13442_112);

  function func_13442_112(e) {
    e.stopPropagation();

    document.querySelector("#id-13").classList.add("animationClass-13");
    document.querySelector("#id-13860").classList.add("animationClass-13860");
    document.querySelector("#id-412").classList.add("animationClass-412");
    document.querySelector("#id-410").classList.add("animationClass-410");
    document.querySelector("#id-416").classList.add("animationClass-416");
    document.querySelector("#id-174").classList.add("animationClass-174");
    document.querySelector("#id-175").classList.add("animationClass-175");
    document
      .querySelector(".selfcomposed-1-13702-0")
      .classList.add("animationClass-176-176-0");
    document.querySelector("#id-176").classList.add("animationClass-176");
    document.querySelector("#id-1320").classList.add("animationClass-null1320");
    document.querySelector("#id-115").classList.add("animationClass-null115");
    document.querySelector("#id-180").classList.add("animationClass-null180");
    document.querySelector("#id-726").classList.add("animationClass-null726");
    document.querySelector("#id-725").classList.add("animationClass-null725");
    document.querySelector("#id-116").classList.add("animationClass-null116");
    document.querySelector("#id-1321").classList.add("animationClass-null1321");
    document.querySelector("#id-723").classList.add("animationClass-null723");
    document.querySelector("#id-72").classList.add("animationClass-null72");
    document.querySelector("#id-713").classList.add("animationClass-null713");
    document.querySelector("#id-711").classList.add("animationClass-null711");
    document.querySelector("#id-712").classList.add("animationClass-null712");
    document.querySelector("#id-724").classList.add("animationClass-null724");
    document.querySelector("#id-117").classList.add("animationClass-null117");
    document.querySelector("#id-1322").classList.add("animationClass-null1322");
    document.querySelector("#id-722").classList.add("animationClass-null722");
    document.querySelector("#id-73").classList.add("animationClass-null73");
    document.querySelector("#id-715").classList.add("animationClass-null715");
    document.querySelector("#id-716").classList.add("animationClass-null716");
    document.querySelector("#id-717").classList.add("animationClass-null717");
    document.querySelector("#id-721").classList.add("animationClass-null721");
    document.querySelector("#id-74").classList.add("animationClass-null74");
    document.querySelector("#id-718").classList.add("animationClass-null718");
    document.querySelector("#id-719").classList.add("animationClass-null719");
    document.querySelector("#id-720").classList.add("animationClass-null720");
    document.querySelector("#id-13215").classList.add("nullAnimation-13215");
    document.querySelector("#id-13216").classList.add("nullAnimation-13216");
    document.querySelector("#id-13217").classList.add("nullAnimation-13217");
    document.querySelector("#id-13218").classList.add("nullAnimation-13218");
    document.querySelector("#id-13219").classList.add("nullAnimation-13219");
    document.querySelector("#id-13220").classList.add("nullAnimation-13220");
    document.querySelector("#id-13221").classList.add("nullAnimation-13221");
    document.querySelector("#id-13222").classList.add("nullAnimation-13222");
    document.querySelector("#id-13223").classList.add("nullAnimation-13223");
    document.querySelector("#id-13224").classList.add("nullAnimation-13224");
    document.querySelector("#id-13225").classList.add("nullAnimation-13225");
    document.querySelector("#id-13226").classList.add("nullAnimation-13226");
    document.querySelector("#id-13227").classList.add("nullAnimation-13227");
    document.querySelector("#id-114").classList.add("animationClass-null114");
    document.querySelector("#id-13441").classList.add("animationClass-13441");
    document.querySelector("#id-13442").classList.add("animationClass-13442");
    document.querySelector("#id-13443").classList.add("animationClass-13443");
    document
      .querySelector(".home-1-403648-0")
      .classList.add("animationClass-13444-13444-0");
    document.querySelector("#id-13444").classList.add("animationClass-13444");
    document.querySelector("#id-13445").classList.add("animationClass-13445");
    document.querySelector("#id-13446").classList.add("animationClass-13446");
    document
      .querySelector(".journaling-1-639000-0")
      .classList.add("animationClass-13447-13447-0");
    document.querySelector("#id-13447").classList.add("animationClass-13447");
    document.querySelector("#id-13448").classList.add("animationClass-13448");
    document.querySelector("#id-13449").classList.add("animationClass-13449");
    document
      .querySelector(".selfcare-1-16600-0")
      .classList.add("animationClass-13450-13450-0");
    document.querySelector("#id-13450").classList.add("animationClass-13450");
    document.querySelector("#id-13451").classList.add("animationClass-13451");
    document.querySelector("#id-13452").classList.add("animationClass-13452");
    document
      .querySelector(".profile-1-46475-0")
      .classList.add("animationClass-13453-13453-0");
    document.querySelector("#id-13453").classList.add("animationClass-13453");
    document
      .querySelector("#id-13442")
      .removeEventListener("click", func_13442_112);

    setTimeout(() => {
      document
        .querySelector("#id-13442")
        .addEventListener("click", func_13442_112);
    }, 100);
  }

  function func_13442_112(e) {
    e.stopPropagation();

    document.querySelector("#id-13").classList.add("animationClass-112");
    document.querySelector("#id-13860").classList.add("nullAnimation-13860");
    document.querySelector("#id-412").classList.add("nullAnimation-412");
    document.querySelector("#id-410").classList.add("nullAnimation-410");
    document.querySelector("#id-416").classList.add("nullAnimation-416");
    document.querySelector("#id-174").classList.add("animationClass-163");
    document.querySelector("#id-175").classList.add("animationClass-119");
    document
      .querySelector(".selfcomposed-1-13702-0")
      .classList.add("animationClass-120-120-0");
    document.querySelector("#id-176").classList.add("animationClass-120");
    document.querySelector("#id-1320").classList.add("animationClass-1320");
    document.querySelector("#id-115").classList.add("animationClass-115");
    document
      .querySelector(".how-are-you-fee-1-604632-0")
      .classList.add("animationClass-180-180-0");
    document.querySelector("#id-180").classList.add("animationClass-180");
    document.querySelector("#id-726").classList.add("animationClass-726");
    document.querySelector("#id-725").classList.add("animationClass-725");
    document.querySelector("#id-116").classList.add("animationClass-116");
    document
      .querySelector(".journaling-prom-2-123806-0")
      .classList.add("animationClass-1321-1321-0");
    document.querySelector("#id-1321").classList.add("animationClass-1321");
    document.querySelector("#id-723").classList.add("animationClass-723");
    document.querySelector("#id-72").classList.add("animationClass-72");
    document.querySelector("#id-713").classList.add("animationClass-713");
    document.querySelector("#id-711").classList.add("animationClass-711");
    document.querySelector("#id-712").classList.add("animationClass-712");
    document.querySelector("#id-724").classList.add("animationClass-724");
    document.querySelector("#id-117").classList.add("animationClass-117");
    document
      .querySelector(".daily-tasks-1-31620-0")
      .classList.add("animationClass-1322-1322-0");
    document.querySelector("#id-1322").classList.add("animationClass-1322");
    document.querySelector("#id-722").classList.add("animationClass-722");
    document.querySelector("#id-73").classList.add("animationClass-73");
    document.querySelector("#id-715").classList.add("animationClass-715");
    document.querySelector("#id-716").classList.add("animationClass-716");
    document.querySelector("#id-717").classList.add("animationClass-717");
    document.querySelector("#id-721").classList.add("animationClass-721");
    document.querySelector("#id-74").classList.add("animationClass-74");
    document.querySelector("#id-718").classList.add("animationClass-718");
    document.querySelector("#id-719").classList.add("animationClass-719");
    document.querySelector("#id-720").classList.add("animationClass-720");
    document
      .querySelector("#id-13215")
      .classList.add("animationClass-null13215");
    document
      .querySelector("#id-13216")
      .classList.add("animationClass-null13216");
    document
      .querySelector("#id-13217")
      .classList.add("animationClass-null13217");
    document
      .querySelector("#id-13218")
      .classList.add("animationClass-null13218");
    document
      .querySelector("#id-13219")
      .classList.add("animationClass-null13219");
    document
      .querySelector("#id-13220")
      .classList.add("animationClass-null13220");
    document
      .querySelector("#id-13221")
      .classList.add("animationClass-null13221");
    document
      .querySelector("#id-13222")
      .classList.add("animationClass-null13222");
    document
      .querySelector("#id-13223")
      .classList.add("animationClass-null13223");
    document
      .querySelector("#id-13224")
      .classList.add("animationClass-null13224");
    document
      .querySelector("#id-13225")
      .classList.add("animationClass-null13225");
    document
      .querySelector("#id-13226")
      .classList.add("animationClass-null13226");
    document
      .querySelector("#id-13227")
      .classList.add("animationClass-null13227");
    document
      .querySelector(".hello-user1-0-416724-0")
      .classList.add("animationClass-114-114-0");
    document.querySelector("#id-114").classList.add("animationClass-114");
    document.querySelector("#id-13441").classList.add("animationClass-13215");
    document
      .querySelector("#id-13442")
      .removeEventListener("click", func_13442_112);

    setTimeout(() => {
      //loop login
      document.querySelector("#id-13").classList.remove("animationClass-13");
      document
        .querySelector("#id-13860")
        .classList.remove("animationClass-13860");
      document.querySelector("#id-412").classList.remove("animationClass-412");
      document.querySelector("#id-410").classList.remove("animationClass-410");
      document.querySelector("#id-416").classList.remove("animationClass-416");
      document.querySelector("#id-174").classList.remove("animationClass-174");
      document.querySelector("#id-175").classList.remove("animationClass-175");
      document
        .querySelector(".selfcomposed-1-13702-0")
        .classList.remove("animationClass-176-176-0");
      document.querySelector("#id-176").classList.remove("animationClass-176");
      document
        .querySelector("#id-1320")
        .classList.remove("animationClass-null1320");
      document
        .querySelector("#id-115")
        .classList.remove("animationClass-null115");
      document
        .querySelector("#id-180")
        .classList.remove("animationClass-null180");
      document
        .querySelector("#id-726")
        .classList.remove("animationClass-null726");
      document
        .querySelector("#id-725")
        .classList.remove("animationClass-null725");
      document
        .querySelector("#id-116")
        .classList.remove("animationClass-null116");
      document
        .querySelector("#id-1321")
        .classList.remove("animationClass-null1321");
      document
        .querySelector("#id-723")
        .classList.remove("animationClass-null723");
      document
        .querySelector("#id-72")
        .classList.remove("animationClass-null72");
      document
        .querySelector("#id-713")
        .classList.remove("animationClass-null713");
      document
        .querySelector("#id-711")
        .classList.remove("animationClass-null711");
      document
        .querySelector("#id-712")
        .classList.remove("animationClass-null712");
      document
        .querySelector("#id-724")
        .classList.remove("animationClass-null724");
      document
        .querySelector("#id-117")
        .classList.remove("animationClass-null117");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-null1322");
      document
        .querySelector("#id-722")
        .classList.remove("animationClass-null722");
      document
        .querySelector("#id-73")
        .classList.remove("animationClass-null73");
      document
        .querySelector("#id-715")
        .classList.remove("animationClass-null715");
      document
        .querySelector("#id-716")
        .classList.remove("animationClass-null716");
      document
        .querySelector("#id-717")
        .classList.remove("animationClass-null717");
      document
        .querySelector("#id-721")
        .classList.remove("animationClass-null721");
      document
        .querySelector("#id-74")
        .classList.remove("animationClass-null74");
      document
        .querySelector("#id-718")
        .classList.remove("animationClass-null718");
      document
        .querySelector("#id-719")
        .classList.remove("animationClass-null719");
      document
        .querySelector("#id-720")
        .classList.remove("animationClass-null720");
      document
        .querySelector("#id-13215")
        .classList.remove("nullAnimation-13215");
      document
        .querySelector("#id-13216")
        .classList.remove("nullAnimation-13216");
      document
        .querySelector("#id-13217")
        .classList.remove("nullAnimation-13217");
      document
        .querySelector("#id-13218")
        .classList.remove("nullAnimation-13218");
      document
        .querySelector("#id-13219")
        .classList.remove("nullAnimation-13219");
      document
        .querySelector("#id-13220")
        .classList.remove("nullAnimation-13220");
      document
        .querySelector("#id-13221")
        .classList.remove("nullAnimation-13221");
      document
        .querySelector("#id-13222")
        .classList.remove("nullAnimation-13222");
      document
        .querySelector("#id-13223")
        .classList.remove("nullAnimation-13223");
      document
        .querySelector("#id-13224")
        .classList.remove("nullAnimation-13224");
      document
        .querySelector("#id-13225")
        .classList.remove("nullAnimation-13225");
      document
        .querySelector("#id-13226")
        .classList.remove("nullAnimation-13226");
      document
        .querySelector("#id-13227")
        .classList.remove("nullAnimation-13227");
      document
        .querySelector("#id-114")
        .classList.remove("animationClass-null114");
      document
        .querySelector("#id-13441")
        .classList.remove("animationClass-13441");
      document
        .querySelector("#id-13442")
        .classList.remove("animationClass-13442");
      document
        .querySelector("#id-13443")
        .classList.remove("animationClass-13443");
      document
        .querySelector(".home-1-403648-0")
        .classList.remove("animationClass-13444-13444-0");
      document
        .querySelector("#id-13444")
        .classList.remove("animationClass-13444");
      document
        .querySelector("#id-13445")
        .classList.remove("animationClass-13445");
      document
        .querySelector("#id-13446")
        .classList.remove("animationClass-13446");
      document
        .querySelector(".journaling-1-639000-0")
        .classList.remove("animationClass-13447-13447-0");
      document
        .querySelector("#id-13447")
        .classList.remove("animationClass-13447");
      document
        .querySelector("#id-13448")
        .classList.remove("animationClass-13448");
      document
        .querySelector("#id-13449")
        .classList.remove("animationClass-13449");
      document
        .querySelector(".selfcare-1-16600-0")
        .classList.remove("animationClass-13450-13450-0");
      document
        .querySelector("#id-13450")
        .classList.remove("animationClass-13450");
      document
        .querySelector("#id-13451")
        .classList.remove("animationClass-13451");
      document
        .querySelector("#id-13452")
        .classList.remove("animationClass-13452");
      document
        .querySelector(".profile-1-46475-0")
        .classList.remove("animationClass-13453-13453-0");
      document
        .querySelector("#id-13453")
        .classList.remove("animationClass-13453");
      document.querySelector("#id-13").classList.remove("animationClass-112");
      document
        .querySelector("#id-13860")
        .classList.remove("nullAnimation-13860");
      document.querySelector("#id-412").classList.remove("nullAnimation-412");
      document.querySelector("#id-410").classList.remove("nullAnimation-410");
      document.querySelector("#id-416").classList.remove("nullAnimation-416");
      document.querySelector("#id-174").classList.remove("animationClass-163");
      document.querySelector("#id-175").classList.remove("animationClass-119");
      document
        .querySelector(".selfcomposed-1-13702-0")
        .classList.remove("animationClass-120-120-0");
      document.querySelector("#id-176").classList.remove("animationClass-120");
      document
        .querySelector("#id-1320")
        .classList.remove("animationClass-1320");
      document.querySelector("#id-115").classList.remove("animationClass-115");
      document
        .querySelector(".how-are-you-fee-1-604632-0")
        .classList.remove("animationClass-180-180-0");
      document.querySelector("#id-180").classList.remove("animationClass-180");
      document.querySelector("#id-726").classList.remove("animationClass-726");
      document.querySelector("#id-725").classList.remove("animationClass-725");
      document.querySelector("#id-116").classList.remove("animationClass-116");
      document
        .querySelector(".journaling-prom-2-123806-0")
        .classList.remove("animationClass-1321-1321-0");
      document
        .querySelector("#id-1321")
        .classList.remove("animationClass-1321");
      document.querySelector("#id-723").classList.remove("animationClass-723");
      document.querySelector("#id-72").classList.remove("animationClass-72");
      document.querySelector("#id-713").classList.remove("animationClass-713");
      document.querySelector("#id-711").classList.remove("animationClass-711");
      document.querySelector("#id-712").classList.remove("animationClass-712");
      document.querySelector("#id-724").classList.remove("animationClass-724");
      document.querySelector("#id-117").classList.remove("animationClass-117");
      document
        .querySelector(".daily-tasks-1-31620-0")
        .classList.remove("animationClass-1322-1322-0");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-1322");
      document.querySelector("#id-722").classList.remove("animationClass-722");
      document.querySelector("#id-73").classList.remove("animationClass-73");
      document.querySelector("#id-715").classList.remove("animationClass-715");
      document.querySelector("#id-716").classList.remove("animationClass-716");
      document.querySelector("#id-717").classList.remove("animationClass-717");
      document.querySelector("#id-721").classList.remove("animationClass-721");
      document.querySelector("#id-74").classList.remove("animationClass-74");
      document.querySelector("#id-718").classList.remove("animationClass-718");
      document.querySelector("#id-719").classList.remove("animationClass-719");
      document.querySelector("#id-720").classList.remove("animationClass-720");
      document
        .querySelector("#id-13215")
        .classList.remove("animationClass-null13215");
      document
        .querySelector("#id-13216")
        .classList.remove("animationClass-null13216");
      document
        .querySelector("#id-13217")
        .classList.remove("animationClass-null13217");
      document
        .querySelector("#id-13218")
        .classList.remove("animationClass-null13218");
      document
        .querySelector("#id-13219")
        .classList.remove("animationClass-null13219");
      document
        .querySelector("#id-13220")
        .classList.remove("animationClass-null13220");
      document
        .querySelector("#id-13221")
        .classList.remove("animationClass-null13221");
      document
        .querySelector("#id-13222")
        .classList.remove("animationClass-null13222");
      document
        .querySelector("#id-13223")
        .classList.remove("animationClass-null13223");
      document
        .querySelector("#id-13224")
        .classList.remove("animationClass-null13224");
      document
        .querySelector("#id-13225")
        .classList.remove("animationClass-null13225");
      document
        .querySelector("#id-13226")
        .classList.remove("animationClass-null13226");
      document
        .querySelector("#id-13227")
        .classList.remove("animationClass-null13227");
      document
        .querySelector(".hello-user1-0-416724-0")
        .classList.remove("animationClass-114-114-0");
      document.querySelector("#id-114").classList.remove("animationClass-114");
      document
        .querySelector("#id-13441")
        .classList.remove("animationClass-13215");
      runAnimations();
    }, 300);
  }
}
export default runAnimations;
// links object
export const allLinks = {};

// function object
export const allFunctions = {};
