function runAnimations() {
  document.querySelector("#id-13760").addEventListener("click", func_13760_13);

  function func_13760_13(e) {
    e.stopPropagation();

    document.querySelector("#id-12").classList.add("animationClass-12");
    document.querySelector("#id-48").classList.add("animationClass-48");
    document.querySelector("#id-13760").classList.add("animationClass-13760");
    document.querySelector("#id-83").classList.add("animationClass-83");
    document.querySelector("#id-13759").classList.add("animationClass-13759");
    document.querySelector("#id-13764").classList.add("animationClass-13764");
    document
      .querySelector("#id-13860")
      .classList.add("animationClass-null13860");
    document.querySelector("#id-32").classList.add("animationClass-32");
    document.querySelector("#id-37").classList.add("animationClass-37");
    document.querySelector("#id-49").classList.add("animationClass-49");
    document
      .querySelector(".create-your-own-1-363600-0")
      .classList.add("animationClass-13761-13761-0");
    document.querySelector("#id-13761").classList.add("animationClass-13761");
    document.querySelector("#id-177").classList.add("animationClass-177");
    document.querySelector("#id-178").classList.add("animationClass-178");
    document
      .querySelector(".selfcomposed-1-72680-0")
      .classList.add("animationClass-179-179-0");
    document.querySelector("#id-179").classList.add("animationClass-179");
    document.querySelector("#id-1320").classList.add("nullAnimation-1320");
    document.querySelector("#id-115").classList.add("nullAnimation-115");
    document.querySelector("#id-180").classList.add("nullAnimation-180");
    document.querySelector("#id-726").classList.add("nullAnimation-726");
    document.querySelector("#id-725").classList.add("nullAnimation-725");
    document.querySelector("#id-116").classList.add("nullAnimation-116");
    document.querySelector("#id-1321").classList.add("nullAnimation-1321");
    document.querySelector("#id-723").classList.add("nullAnimation-723");
    document.querySelector("#id-72").classList.add("nullAnimation-72");
    document.querySelector("#id-713").classList.add("nullAnimation-713");
    document.querySelector("#id-711").classList.add("nullAnimation-711");
    document.querySelector("#id-712").classList.add("nullAnimation-712");
    document.querySelector("#id-724").classList.add("nullAnimation-724");
    document.querySelector("#id-117").classList.add("nullAnimation-117");
    document.querySelector("#id-1322").classList.add("nullAnimation-1322");
    document.querySelector("#id-722").classList.add("nullAnimation-722");
    document.querySelector("#id-73").classList.add("nullAnimation-73");
    document.querySelector("#id-715").classList.add("nullAnimation-715");
    document.querySelector("#id-716").classList.add("nullAnimation-716");
    document.querySelector("#id-717").classList.add("nullAnimation-717");
    document.querySelector("#id-721").classList.add("nullAnimation-721");
    document.querySelector("#id-74").classList.add("nullAnimation-74");
    document.querySelector("#id-718").classList.add("nullAnimation-718");
    document.querySelector("#id-719").classList.add("nullAnimation-719");
    document.querySelector("#id-720").classList.add("nullAnimation-720");
    document.querySelector("#id-13215").classList.add("nullAnimation-13215");
    document.querySelector("#id-13216").classList.add("nullAnimation-13216");
    document.querySelector("#id-13217").classList.add("nullAnimation-13217");
    document.querySelector("#id-13218").classList.add("nullAnimation-13218");
    document.querySelector("#id-13219").classList.add("nullAnimation-13219");
    document.querySelector("#id-13220").classList.add("nullAnimation-13220");
    document.querySelector("#id-13221").classList.add("nullAnimation-13221");
    document.querySelector("#id-13222").classList.add("nullAnimation-13222");
    document.querySelector("#id-13223").classList.add("nullAnimation-13223");
    document.querySelector("#id-13224").classList.add("nullAnimation-13224");
    document.querySelector("#id-13225").classList.add("nullAnimation-13225");
    document.querySelector("#id-13226").classList.add("nullAnimation-13226");
    document.querySelector("#id-13227").classList.add("nullAnimation-13227");
    document.querySelector("#id-412").classList.add("animationClass-null412");
    document.querySelector("#id-416").classList.add("animationClass-null416");
    document.querySelector("#id-114").classList.add("nullAnimation-114");
    document.querySelector("#id-13428").classList.add("animationClass-13428");
    document.querySelector("#id-13429").classList.add("animationClass-13429");
    document.querySelector("#id-13430").classList.add("animationClass-13430");
    document
      .querySelector(".home-1-258125-0")
      .classList.add("animationClass-13431-13431-0");
    document.querySelector("#id-13431").classList.add("animationClass-13431");
    document.querySelector("#id-13432").classList.add("animationClass-13432");
    document.querySelector("#id-13433").classList.add("animationClass-13433");
    document
      .querySelector(".journaling-1-353990-0")
      .classList.add("animationClass-13434-13434-0");
    document.querySelector("#id-13434").classList.add("animationClass-13434");
    document.querySelector("#id-13435").classList.add("animationClass-13435");
    document.querySelector("#id-13436").classList.add("animationClass-13436");
    document
      .querySelector(".selfcare-1-499140-0")
      .classList.add("animationClass-13437-13437-0");
    document.querySelector("#id-13437").classList.add("animationClass-13437");
    document.querySelector("#id-13438").classList.add("animationClass-13438");
    document.querySelector("#id-13439").classList.add("animationClass-13439");
    document
      .querySelector(".profile-1-256932-0")
      .classList.add("animationClass-13440-13440-0");
    document.querySelector("#id-13440").classList.add("animationClass-13440");
    document
      .querySelector("#id-13760")
      .removeEventListener("click", func_13760_13);

    setTimeout(() => {
      document
        .querySelector("#id-13429")
        .addEventListener("click", func_13429_112);
    }, 100);
  }

  function func_13429_112(e) {
    e.stopPropagation();

    document.querySelector("#id-12").classList.add("animationClass-13");
    document.querySelector("#id-48").classList.add("nullAnimation-48");
    document.querySelector("#id-13760").classList.add("nullAnimation-13760");
    document.querySelector("#id-83").classList.add("nullAnimation-83");
    document.querySelector("#id-13759").classList.add("nullAnimation-13759");
    document.querySelector("#id-13764").classList.add("nullAnimation-13764");
    document.querySelector("#id-13860").classList.add("animationClass-13860");
    document.querySelector("#id-32").classList.add("nullAnimation-32");
    document.querySelector("#id-37").classList.add("nullAnimation-37");
    document.querySelector("#id-49").classList.add("nullAnimation-49");
    document.querySelector("#id-13761").classList.add("animationClass-410");
    document.querySelector("#id-177").classList.add("animationClass-174");
    document.querySelector("#id-178").classList.add("animationClass-175");
    document
      .querySelector(".selfcomposed-1-72680-0")
      .classList.add("animationClass-176-176-0");
    document.querySelector("#id-179").classList.add("animationClass-176");
    document.querySelector("#id-1320").classList.add("animationClass-null1320");
    document.querySelector("#id-115").classList.add("animationClass-null115");
    document.querySelector("#id-180").classList.add("animationClass-null180");
    document.querySelector("#id-726").classList.add("animationClass-null726");
    document.querySelector("#id-725").classList.add("animationClass-null725");
    document.querySelector("#id-116").classList.add("animationClass-null116");
    document.querySelector("#id-1321").classList.add("animationClass-null1321");
    document.querySelector("#id-723").classList.add("animationClass-null723");
    document.querySelector("#id-72").classList.add("animationClass-null72");
    document.querySelector("#id-713").classList.add("animationClass-null713");
    document.querySelector("#id-711").classList.add("animationClass-null711");
    document.querySelector("#id-712").classList.add("animationClass-null712");
    document.querySelector("#id-724").classList.add("animationClass-null724");
    document.querySelector("#id-117").classList.add("animationClass-null117");
    document.querySelector("#id-1322").classList.add("animationClass-null1322");
    document.querySelector("#id-722").classList.add("animationClass-null722");
    document.querySelector("#id-73").classList.add("animationClass-null73");
    document.querySelector("#id-715").classList.add("animationClass-null715");
    document.querySelector("#id-716").classList.add("animationClass-null716");
    document.querySelector("#id-717").classList.add("animationClass-null717");
    document.querySelector("#id-721").classList.add("animationClass-null721");
    document.querySelector("#id-74").classList.add("animationClass-null74");
    document.querySelector("#id-718").classList.add("animationClass-null718");
    document.querySelector("#id-719").classList.add("animationClass-null719");
    document.querySelector("#id-720").classList.add("animationClass-null720");
    document
      .querySelector("#id-13215")
      .classList.add("animationClass-null13215");
    document
      .querySelector("#id-13216")
      .classList.add("animationClass-null13216");
    document
      .querySelector("#id-13217")
      .classList.add("animationClass-null13217");
    document
      .querySelector("#id-13218")
      .classList.add("animationClass-null13218");
    document
      .querySelector("#id-13219")
      .classList.add("animationClass-null13219");
    document
      .querySelector("#id-13220")
      .classList.add("animationClass-null13220");
    document
      .querySelector("#id-13221")
      .classList.add("animationClass-null13221");
    document
      .querySelector("#id-13222")
      .classList.add("animationClass-null13222");
    document
      .querySelector("#id-13223")
      .classList.add("animationClass-null13223");
    document
      .querySelector("#id-13224")
      .classList.add("animationClass-null13224");
    document
      .querySelector("#id-13225")
      .classList.add("animationClass-null13225");
    document
      .querySelector("#id-13226")
      .classList.add("animationClass-null13226");
    document
      .querySelector("#id-13227")
      .classList.add("animationClass-null13227");
    document.querySelector("#id-412").classList.add("animationClass-412");
    document.querySelector("#id-416").classList.add("animationClass-416");
    document.querySelector("#id-114").classList.add("animationClass-null114");
    document.querySelector("#id-13428").classList.add("animationClass-13441");
    document
      .querySelector("#id-13429")
      .removeEventListener("click", func_13429_112);

    setTimeout(() => {
      document
        .querySelector("#id-13216")
        .addEventListener("click", func_13216_112);
    }, 100);
  }

  function func_13216_112(e) {
    e.stopPropagation();

    document.querySelector("#id-12").classList.add("animationClass-112");
    document.querySelector("#id-13860").classList.add("nullAnimation-13860");
    document.querySelector("#id-13761").classList.add("nullAnimation-13761");
    document.querySelector("#id-177").classList.add("animationClass-163");
    document.querySelector("#id-178").classList.add("animationClass-119");
    document
      .querySelector(".selfcomposed-1-72680-0")
      .classList.add("animationClass-120-120-0");
    document.querySelector("#id-179").classList.add("animationClass-120");
    document.querySelector("#id-1320").classList.add("animationClass-1320");
    document.querySelector("#id-115").classList.add("animationClass-115");
    document
      .querySelector(".how-are-you-fee-1-517205-0")
      .classList.add("animationClass-180-180-0");
    document.querySelector("#id-180").classList.add("animationClass-180");
    document.querySelector("#id-726").classList.add("animationClass-726");
    document.querySelector("#id-725").classList.add("animationClass-725");
    document.querySelector("#id-116").classList.add("animationClass-116");
    document
      .querySelector(".journaling-prom-2-56620-0")
      .classList.add("animationClass-1321-1321-0");
    document.querySelector("#id-1321").classList.add("animationClass-1321");
    document.querySelector("#id-723").classList.add("animationClass-723");
    document.querySelector("#id-72").classList.add("animationClass-72");
    document.querySelector("#id-713").classList.add("animationClass-713");
    document.querySelector("#id-711").classList.add("animationClass-711");
    document.querySelector("#id-712").classList.add("animationClass-712");
    document.querySelector("#id-724").classList.add("animationClass-724");
    document.querySelector("#id-117").classList.add("animationClass-117");
    document
      .querySelector(".daily-tasks-1-222748-0")
      .classList.add("animationClass-1322-1322-0");
    document.querySelector("#id-1322").classList.add("animationClass-1322");
    document.querySelector("#id-722").classList.add("animationClass-722");
    document.querySelector("#id-73").classList.add("animationClass-73");
    document.querySelector("#id-715").classList.add("animationClass-715");
    document.querySelector("#id-716").classList.add("animationClass-716");
    document.querySelector("#id-717").classList.add("animationClass-717");
    document.querySelector("#id-721").classList.add("animationClass-721");
    document.querySelector("#id-74").classList.add("animationClass-74");
    document.querySelector("#id-718").classList.add("animationClass-718");
    document.querySelector("#id-719").classList.add("animationClass-719");
    document.querySelector("#id-720").classList.add("animationClass-720");
    document.querySelector("#id-13215").classList.add("animationClass-13215");
    document.querySelector("#id-13216").classList.add("animationClass-13216");
    document.querySelector("#id-13217").classList.add("animationClass-13217");
    document
      .querySelector(".home-1-212212-0")
      .classList.add("animationClass-13218-13218-0");
    document.querySelector("#id-13218").classList.add("animationClass-13218");
    document.querySelector("#id-13219").classList.add("animationClass-13219");
    document.querySelector("#id-13220").classList.add("animationClass-13220");
    document
      .querySelector(".journaling-1-172528-0")
      .classList.add("animationClass-13221-13221-0");
    document.querySelector("#id-13221").classList.add("animationClass-13221");
    document.querySelector("#id-13222").classList.add("animationClass-13222");
    document.querySelector("#id-13223").classList.add("animationClass-13223");
    document
      .querySelector(".selfcare-1-117711-0")
      .classList.add("animationClass-13224-13224-0");
    document.querySelector("#id-13224").classList.add("animationClass-13224");
    document.querySelector("#id-13225").classList.add("animationClass-13225");
    document.querySelector("#id-13226").classList.add("animationClass-13226");
    document
      .querySelector(".profile-1-28623-0")
      .classList.add("animationClass-13227-13227-0");
    document.querySelector("#id-13227").classList.add("animationClass-13227");
    document.querySelector("#id-412").classList.add("nullAnimation-412");
    document.querySelector("#id-416").classList.add("nullAnimation-416");
    document
      .querySelector(".hello-user1-0-31200-0")
      .classList.add("animationClass-114-114-0");
    document.querySelector("#id-114").classList.add("animationClass-114");
    document.querySelector("#id-13428").classList.add("nullAnimation-13428");
    document
      .querySelector("#id-13216")
      .removeEventListener("click", func_13216_112);

    setTimeout(() => {
      //loop login
      document.querySelector("#id-12").classList.remove("animationClass-12");
      document.querySelector("#id-48").classList.remove("animationClass-48");
      document
        .querySelector("#id-13760")
        .classList.remove("animationClass-13760");
      document.querySelector("#id-83").classList.remove("animationClass-83");
      document
        .querySelector("#id-13759")
        .classList.remove("animationClass-13759");
      document
        .querySelector("#id-13764")
        .classList.remove("animationClass-13764");
      document
        .querySelector("#id-13860")
        .classList.remove("animationClass-null13860");
      document.querySelector("#id-32").classList.remove("animationClass-32");
      document.querySelector("#id-37").classList.remove("animationClass-37");
      document.querySelector("#id-49").classList.remove("animationClass-49");
      document
        .querySelector(".create-your-own-1-363600-0")
        .classList.remove("animationClass-13761-13761-0");
      document
        .querySelector("#id-13761")
        .classList.remove("animationClass-13761");
      document.querySelector("#id-177").classList.remove("animationClass-177");
      document.querySelector("#id-178").classList.remove("animationClass-178");
      document
        .querySelector(".selfcomposed-1-72680-0")
        .classList.remove("animationClass-179-179-0");
      document.querySelector("#id-179").classList.remove("animationClass-179");
      document.querySelector("#id-1320").classList.remove("nullAnimation-1320");
      document.querySelector("#id-115").classList.remove("nullAnimation-115");
      document.querySelector("#id-180").classList.remove("nullAnimation-180");
      document.querySelector("#id-726").classList.remove("nullAnimation-726");
      document.querySelector("#id-725").classList.remove("nullAnimation-725");
      document.querySelector("#id-116").classList.remove("nullAnimation-116");
      document.querySelector("#id-1321").classList.remove("nullAnimation-1321");
      document.querySelector("#id-723").classList.remove("nullAnimation-723");
      document.querySelector("#id-72").classList.remove("nullAnimation-72");
      document.querySelector("#id-713").classList.remove("nullAnimation-713");
      document.querySelector("#id-711").classList.remove("nullAnimation-711");
      document.querySelector("#id-712").classList.remove("nullAnimation-712");
      document.querySelector("#id-724").classList.remove("nullAnimation-724");
      document.querySelector("#id-117").classList.remove("nullAnimation-117");
      document.querySelector("#id-1322").classList.remove("nullAnimation-1322");
      document.querySelector("#id-722").classList.remove("nullAnimation-722");
      document.querySelector("#id-73").classList.remove("nullAnimation-73");
      document.querySelector("#id-715").classList.remove("nullAnimation-715");
      document.querySelector("#id-716").classList.remove("nullAnimation-716");
      document.querySelector("#id-717").classList.remove("nullAnimation-717");
      document.querySelector("#id-721").classList.remove("nullAnimation-721");
      document.querySelector("#id-74").classList.remove("nullAnimation-74");
      document.querySelector("#id-718").classList.remove("nullAnimation-718");
      document.querySelector("#id-719").classList.remove("nullAnimation-719");
      document.querySelector("#id-720").classList.remove("nullAnimation-720");
      document
        .querySelector("#id-13215")
        .classList.remove("nullAnimation-13215");
      document
        .querySelector("#id-13216")
        .classList.remove("nullAnimation-13216");
      document
        .querySelector("#id-13217")
        .classList.remove("nullAnimation-13217");
      document
        .querySelector("#id-13218")
        .classList.remove("nullAnimation-13218");
      document
        .querySelector("#id-13219")
        .classList.remove("nullAnimation-13219");
      document
        .querySelector("#id-13220")
        .classList.remove("nullAnimation-13220");
      document
        .querySelector("#id-13221")
        .classList.remove("nullAnimation-13221");
      document
        .querySelector("#id-13222")
        .classList.remove("nullAnimation-13222");
      document
        .querySelector("#id-13223")
        .classList.remove("nullAnimation-13223");
      document
        .querySelector("#id-13224")
        .classList.remove("nullAnimation-13224");
      document
        .querySelector("#id-13225")
        .classList.remove("nullAnimation-13225");
      document
        .querySelector("#id-13226")
        .classList.remove("nullAnimation-13226");
      document
        .querySelector("#id-13227")
        .classList.remove("nullAnimation-13227");
      document
        .querySelector("#id-412")
        .classList.remove("animationClass-null412");
      document
        .querySelector("#id-416")
        .classList.remove("animationClass-null416");
      document.querySelector("#id-114").classList.remove("nullAnimation-114");
      document
        .querySelector("#id-13428")
        .classList.remove("animationClass-13428");
      document
        .querySelector("#id-13429")
        .classList.remove("animationClass-13429");
      document
        .querySelector("#id-13430")
        .classList.remove("animationClass-13430");
      document
        .querySelector(".home-1-258125-0")
        .classList.remove("animationClass-13431-13431-0");
      document
        .querySelector("#id-13431")
        .classList.remove("animationClass-13431");
      document
        .querySelector("#id-13432")
        .classList.remove("animationClass-13432");
      document
        .querySelector("#id-13433")
        .classList.remove("animationClass-13433");
      document
        .querySelector(".journaling-1-353990-0")
        .classList.remove("animationClass-13434-13434-0");
      document
        .querySelector("#id-13434")
        .classList.remove("animationClass-13434");
      document
        .querySelector("#id-13435")
        .classList.remove("animationClass-13435");
      document
        .querySelector("#id-13436")
        .classList.remove("animationClass-13436");
      document
        .querySelector(".selfcare-1-499140-0")
        .classList.remove("animationClass-13437-13437-0");
      document
        .querySelector("#id-13437")
        .classList.remove("animationClass-13437");
      document
        .querySelector("#id-13438")
        .classList.remove("animationClass-13438");
      document
        .querySelector("#id-13439")
        .classList.remove("animationClass-13439");
      document
        .querySelector(".profile-1-256932-0")
        .classList.remove("animationClass-13440-13440-0");
      document
        .querySelector("#id-13440")
        .classList.remove("animationClass-13440");
      document.querySelector("#id-12").classList.remove("animationClass-13");
      document.querySelector("#id-48").classList.remove("nullAnimation-48");
      document
        .querySelector("#id-13760")
        .classList.remove("nullAnimation-13760");
      document.querySelector("#id-83").classList.remove("nullAnimation-83");
      document
        .querySelector("#id-13759")
        .classList.remove("nullAnimation-13759");
      document
        .querySelector("#id-13764")
        .classList.remove("nullAnimation-13764");
      document
        .querySelector("#id-13860")
        .classList.remove("animationClass-13860");
      document.querySelector("#id-32").classList.remove("nullAnimation-32");
      document.querySelector("#id-37").classList.remove("nullAnimation-37");
      document.querySelector("#id-49").classList.remove("nullAnimation-49");
      document
        .querySelector("#id-13761")
        .classList.remove("animationClass-410");
      document.querySelector("#id-177").classList.remove("animationClass-174");
      document.querySelector("#id-178").classList.remove("animationClass-175");
      document
        .querySelector(".selfcomposed-1-72680-0")
        .classList.remove("animationClass-176-176-0");
      document.querySelector("#id-179").classList.remove("animationClass-176");
      document
        .querySelector("#id-1320")
        .classList.remove("animationClass-null1320");
      document
        .querySelector("#id-115")
        .classList.remove("animationClass-null115");
      document
        .querySelector("#id-180")
        .classList.remove("animationClass-null180");
      document
        .querySelector("#id-726")
        .classList.remove("animationClass-null726");
      document
        .querySelector("#id-725")
        .classList.remove("animationClass-null725");
      document
        .querySelector("#id-116")
        .classList.remove("animationClass-null116");
      document
        .querySelector("#id-1321")
        .classList.remove("animationClass-null1321");
      document
        .querySelector("#id-723")
        .classList.remove("animationClass-null723");
      document
        .querySelector("#id-72")
        .classList.remove("animationClass-null72");
      document
        .querySelector("#id-713")
        .classList.remove("animationClass-null713");
      document
        .querySelector("#id-711")
        .classList.remove("animationClass-null711");
      document
        .querySelector("#id-712")
        .classList.remove("animationClass-null712");
      document
        .querySelector("#id-724")
        .classList.remove("animationClass-null724");
      document
        .querySelector("#id-117")
        .classList.remove("animationClass-null117");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-null1322");
      document
        .querySelector("#id-722")
        .classList.remove("animationClass-null722");
      document
        .querySelector("#id-73")
        .classList.remove("animationClass-null73");
      document
        .querySelector("#id-715")
        .classList.remove("animationClass-null715");
      document
        .querySelector("#id-716")
        .classList.remove("animationClass-null716");
      document
        .querySelector("#id-717")
        .classList.remove("animationClass-null717");
      document
        .querySelector("#id-721")
        .classList.remove("animationClass-null721");
      document
        .querySelector("#id-74")
        .classList.remove("animationClass-null74");
      document
        .querySelector("#id-718")
        .classList.remove("animationClass-null718");
      document
        .querySelector("#id-719")
        .classList.remove("animationClass-null719");
      document
        .querySelector("#id-720")
        .classList.remove("animationClass-null720");
      document
        .querySelector("#id-13215")
        .classList.remove("animationClass-null13215");
      document
        .querySelector("#id-13216")
        .classList.remove("animationClass-null13216");
      document
        .querySelector("#id-13217")
        .classList.remove("animationClass-null13217");
      document
        .querySelector("#id-13218")
        .classList.remove("animationClass-null13218");
      document
        .querySelector("#id-13219")
        .classList.remove("animationClass-null13219");
      document
        .querySelector("#id-13220")
        .classList.remove("animationClass-null13220");
      document
        .querySelector("#id-13221")
        .classList.remove("animationClass-null13221");
      document
        .querySelector("#id-13222")
        .classList.remove("animationClass-null13222");
      document
        .querySelector("#id-13223")
        .classList.remove("animationClass-null13223");
      document
        .querySelector("#id-13224")
        .classList.remove("animationClass-null13224");
      document
        .querySelector("#id-13225")
        .classList.remove("animationClass-null13225");
      document
        .querySelector("#id-13226")
        .classList.remove("animationClass-null13226");
      document
        .querySelector("#id-13227")
        .classList.remove("animationClass-null13227");
      document.querySelector("#id-412").classList.remove("animationClass-412");
      document.querySelector("#id-416").classList.remove("animationClass-416");
      document
        .querySelector("#id-114")
        .classList.remove("animationClass-null114");
      document
        .querySelector("#id-13428")
        .classList.remove("animationClass-13441");
      document.querySelector("#id-12").classList.remove("animationClass-112");
      document
        .querySelector("#id-13860")
        .classList.remove("nullAnimation-13860");
      document
        .querySelector("#id-13761")
        .classList.remove("nullAnimation-13761");
      document.querySelector("#id-177").classList.remove("animationClass-163");
      document.querySelector("#id-178").classList.remove("animationClass-119");
      document
        .querySelector(".selfcomposed-1-72680-0")
        .classList.remove("animationClass-120-120-0");
      document.querySelector("#id-179").classList.remove("animationClass-120");
      document
        .querySelector("#id-1320")
        .classList.remove("animationClass-1320");
      document.querySelector("#id-115").classList.remove("animationClass-115");
      document
        .querySelector(".how-are-you-fee-1-517205-0")
        .classList.remove("animationClass-180-180-0");
      document.querySelector("#id-180").classList.remove("animationClass-180");
      document.querySelector("#id-726").classList.remove("animationClass-726");
      document.querySelector("#id-725").classList.remove("animationClass-725");
      document.querySelector("#id-116").classList.remove("animationClass-116");
      document
        .querySelector(".journaling-prom-2-56620-0")
        .classList.remove("animationClass-1321-1321-0");
      document
        .querySelector("#id-1321")
        .classList.remove("animationClass-1321");
      document.querySelector("#id-723").classList.remove("animationClass-723");
      document.querySelector("#id-72").classList.remove("animationClass-72");
      document.querySelector("#id-713").classList.remove("animationClass-713");
      document.querySelector("#id-711").classList.remove("animationClass-711");
      document.querySelector("#id-712").classList.remove("animationClass-712");
      document.querySelector("#id-724").classList.remove("animationClass-724");
      document.querySelector("#id-117").classList.remove("animationClass-117");
      document
        .querySelector(".daily-tasks-1-222748-0")
        .classList.remove("animationClass-1322-1322-0");
      document
        .querySelector("#id-1322")
        .classList.remove("animationClass-1322");
      document.querySelector("#id-722").classList.remove("animationClass-722");
      document.querySelector("#id-73").classList.remove("animationClass-73");
      document.querySelector("#id-715").classList.remove("animationClass-715");
      document.querySelector("#id-716").classList.remove("animationClass-716");
      document.querySelector("#id-717").classList.remove("animationClass-717");
      document.querySelector("#id-721").classList.remove("animationClass-721");
      document.querySelector("#id-74").classList.remove("animationClass-74");
      document.querySelector("#id-718").classList.remove("animationClass-718");
      document.querySelector("#id-719").classList.remove("animationClass-719");
      document.querySelector("#id-720").classList.remove("animationClass-720");
      document
        .querySelector("#id-13215")
        .classList.remove("animationClass-13215");
      document
        .querySelector("#id-13216")
        .classList.remove("animationClass-13216");
      document
        .querySelector("#id-13217")
        .classList.remove("animationClass-13217");
      document
        .querySelector(".home-1-212212-0")
        .classList.remove("animationClass-13218-13218-0");
      document
        .querySelector("#id-13218")
        .classList.remove("animationClass-13218");
      document
        .querySelector("#id-13219")
        .classList.remove("animationClass-13219");
      document
        .querySelector("#id-13220")
        .classList.remove("animationClass-13220");
      document
        .querySelector(".journaling-1-172528-0")
        .classList.remove("animationClass-13221-13221-0");
      document
        .querySelector("#id-13221")
        .classList.remove("animationClass-13221");
      document
        .querySelector("#id-13222")
        .classList.remove("animationClass-13222");
      document
        .querySelector("#id-13223")
        .classList.remove("animationClass-13223");
      document
        .querySelector(".selfcare-1-117711-0")
        .classList.remove("animationClass-13224-13224-0");
      document
        .querySelector("#id-13224")
        .classList.remove("animationClass-13224");
      document
        .querySelector("#id-13225")
        .classList.remove("animationClass-13225");
      document
        .querySelector("#id-13226")
        .classList.remove("animationClass-13226");
      document
        .querySelector(".profile-1-28623-0")
        .classList.remove("animationClass-13227-13227-0");
      document
        .querySelector("#id-13227")
        .classList.remove("animationClass-13227");
      document.querySelector("#id-412").classList.remove("nullAnimation-412");
      document.querySelector("#id-416").classList.remove("nullAnimation-416");
      document
        .querySelector(".hello-user1-0-31200-0")
        .classList.remove("animationClass-114-114-0");
      document.querySelector("#id-114").classList.remove("animationClass-114");
      document
        .querySelector("#id-13428")
        .classList.remove("nullAnimation-13428");
      runAnimations();
    }, 300);
  }
}
export default runAnimations;
// links object
export const allLinks = {};

// function object
export const allFunctions = {};
